print("현재 나이를 입력해주세요.")
age = int(input("당신의 현재 나이는? : "))
print("=" * 30)
print()

print("생일이 지났습니까?")
birth = int(input("지났으면 0 아니면 -1 : "))
while birth not in [0, -1]:
    print("잘못 입력 하셨습니다.")
    print("다시 입력해주세요.")
    birth = int(input("지났으면 0 아니면 -1 : "))

print("=" * 32)
print()
print(f"  {'@ ' * age} ")
print(f"  {'| ' * age} ")
print(f"  {'| ' * age} ")
print(f"&&{'&&' * age}&")
print(f" *{' *' * age} ")
print(f"&&{'&&' * age}&")
print(f" *{' *' * age} ")
print(f"&&{'&&' * age}&")
print()

print(f"당신의 미국 나이는 {age + birth - 1}세 입니다.")